#!/bin/sh

npm i -g \
	typescript \
	typescript-language-server \
	bash-language-server \
	dockerfile-language-server-nodejs \
	vim-language-server

go get \
	github.com/lighttiger2505/sqls

sudo xbps-install -S \
	gopls \
	ccls
