#!/bin/zsh

set -e

npm -g i \
	typescript \
	typescript-language-server \
	bash-language-server \
	yaml-language-server \
	dockerfile-language-server-nodejs \
	vscode-langservers-extracted

wget https://github.com/redhat-developer/vscode-xml/releases/download/0.21.0/lemminx-linux.zip \
	&& unzip lemminx-linux.zip \
	&& mv lemminx-linux ~/.local/bin/lemminx \
	&& trash *.zip
