#!/bin/sh

set -ex 

if efibootmgr | grep "Boot0001\* Void Linux"; then 
	echo "Entry for Void Linux is present"
	efibootmgr -B -b 1
fi 

opts="
	root=/dev/storage/root rw 

	initrd=\initramfs
	resume=/dev/storage/swap

	rd.luks.uuid=7487d1b4-53f3-491b-9e73-63aa8f32bac6                  
	rd.lvm.vg=storage 

	quiet
	loglevel=3
	i915.enable_psr=0
	net.ifnames=0
	vga=current
	udev.log_level=3
"

opts=`echo "${opts}" | xargs`

efibootmgr \
	--disk /dev/nvme0n1 \
	--part 5 \
	--create \
	--label "Void Linux" \
	--loader /vmlinuz \
	--unicode "${opts}" \
	--verbose 
