#!/bin/sh

set -ex 

if efibootmgr | grep "Boot0001\* Void Linux"; then 
	echo "Entry for Void Linux is present"
	efibootmgr -B -b 1
fi 

opts="
	root=/dev/storage/root rw 

	initrd=\initramfs
	resume=/dev/storage/swap

	rd.luks.uuid=9dff7ce9-df99-4d05-a9f7-02d19050fd4f

	rd.lvm.vg=storage 
	rd.lvm.lv=storage/root 
	rd.lvm.lv=storage/home 
	rd.vlm.lv=storage/swap 

	quiet
	loglevel=3
	i915.enable_psr=0
	net.ifnames=0
	vga=current
	udev.log_level=3
"

opts=`echo "${opts}" | xargs`

efibootmgr \
	--disk /dev/nvme0n1 \
	--part 1 \
	--create \
	--label "Void Linux" \
	--loader /vmlinuz \
	--unicode "${opts}" \
	--verbose 
