#!/bin/sh 

set -x 

mkdir -p ~/.config/zsh

ln -s ~/dev/dots/applications  -t ~/.local/share
ln -s ~/dev/dots/bin           -t ~/.local
ln -s ~/dev/dots/zsh/functions -t ~/.config/zsh
ln -s ~/dev/dots/nvim          -t ~/.config
ln -s ~/dev/dots/service       -t ~/.config

ln -s ~/dev/dots/.tmux.conf                ~/.tmux.conf
ln -s ~/dev/dots/.Xresources               ~/.Xresources
ln -s ~/dev/dots/.xinitrc                  ~/.xinitrc
ln -s ~/dev/dots/.xbindkeysrc              ~/.xbindkeysrc
ln -s ~/dev/dots/zsh/.zshenv               ~/.zshenv
ln -s ~/dev/dots/zsh/.zshrc                ~/.config/zsh/.zshrc
ln -s ~/dev/dots/zsh/.dircolors            ~/.config/zsh/.dircolors
ln -s ~/dev/dots/gnupg/gpg-agent.conf      ~/.gnupg
ln -s ~/dev/dots/gnupg/pinentry-dmenu.conf ~/.gnupg

sudo mkdir -p /etc/sv/runsvdir-manfred

sudo ln -s $HOME/dev/dots/xorg/30-touchpad.conf /etc/X11/xorg.conf.d/30-touchpad.conf
sudo ln -s $HOME/dev/dots/xorg/20-intel.conf    /etc/X11/xorg.conf.d/20-intel.conf
sudo ln -s $HOME/dev/dots/runsvdir-manfred      /etc/sv/runsvdir-manfred/run

