#!/bin/sh 

set -x 


mkdir -p ~/.config/zsh
mkdir -p ~/.config/dunst

ln -s ~/dev/dots/applications  -t ~/.local/share
ln -s ~/dev/dots/bin           -t ~/.local
ln -s ~/dev/dots/zsh/functions -t ~/.config/zsh
ln -s ~/dev/dots/nvim          -t ~/.config
ln -s ~/dev/dots/x-service     -t ~/.config
ln -s ~/dev/dots/bat           -t ~/.config
ln -s ~/dev/dots/user-service  -T ~/.config/service

ln -s ~/dev/dots/.tmux.conf                ~/.tmux.conf
ln -s ~/dev/dots/.Xresources               ~/.Xresources
ln -s ~/dev/dots/.xinitrc                  ~/.xinitrc
ln -s ~/dev/dots/.xbindkeysrc              ~/.xbindkeysrc
ln -s ~/dev/dots/zsh/.zshenv               ~/.zshenv
ln -s ~/dev/dots/zsh/.zshrc                ~/.config/zsh/.zshrc
ln -s ~/dev/dots/zsh/.dircolors            ~/.config/zsh/.dircolors
ln -s ~/dev/dots/gnupg/gpg-agent.conf      ~/.gnupg
ln -s ~/dev/dots/gnupg/pinentry-dmenu.conf ~/.gnupg
ln -s ~/dev/dots/xorg/dunstrc              ~/.config/dunst/dunstrc

sudo mkdir -p /etc/sv/runsvdir-manfred

sudo ln -s $HOME/dev/dots/xorg/30-touchpad.conf /etc/X11/xorg.conf.d/30-touchpad.conf
sudo ln -s $HOME/dev/dots/xorg/20-intel.conf    /etc/X11/xorg.conf.d/20-intel.conf
sudo ln -s $HOME/dev/dots/runsvdir-manfred      /etc/sv/runsvdir-manfred/run
sudo ln -s $HOME/dev/dots/kernel.d/cleanup-boot /etc/kernel.d/post-install/99-cleanup-boot

sudo mkdir -p /var/log/socklog/connmand && sudo chmod 2750 /var/log/socklog/connmand
sudo ln -s $HOME/dev/dots/socklog/connmand /var/log/socklog/connmand/config

sudo mkdir -p /var/log/socklog/docker && sudo chmod 2750 /var/log/socklog/docker
sudo ln -s $HOME/dev/dots/socklog/docker /var/log/socklog/docker/config

sudo mkdir -p /etc/connman 
sudo ln -s $HOME/dev/dots/connman/main.conf /etc/connman/main.conf
sudo ln -s $HOME/dev/dots/connman/flags     /etc/sv/connmand/conf

sudo mkdir -p /etc/sv/dbus/control 
sudo ln -s $HOME/dev/dots/dbus/terminate-chromium /etc/sv/dbus/control/t

for  sv in ~/dev/dots/service/*; do 
	sudo ln -s $sv -t /etc/sv
done
