#!/bin/zsh 

if [ ! -n "${SKIP_HOOKS}" ]; then 
  export SKIP_HOOKS=1

	cache_file=~/.cache/tasks
  count=$(task count status:pending)

	if [ $count = "0" ]; then 
		rm -f $cache_file
	else 
		echo $count > $cache_file 
	fi 
fi 
