#!/bin/sh

set -b # enable job control

# Chromium will exit not gracefully when dbus gets killed 
# during poweroff, which leads to an annoying error message 
# on the next startup.

pid=`pgrep -P1 chromium`

pkill chromium &
tail --pid=$pid -f /dev/null

exit 1
