#!/bin/zsh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f $sysresources ]; then
	xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
	xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
	xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
	xmodmap "$usermodmap"
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
	for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

. $HOME/.fehbg                     # set background image
xset -dpms s off                   # disable monitor saving mode
runsvdir $HOME/.config/x-service & # start xorg service
eval $(dbus-launch --sh-syntax)    # setup user dbus session

# TODO set globally or in udev
xset r rate 220 40                 # update keyboard update rate
setxkbmap de                       # set keyboard layout

exec dwm
