#!/bin/sh 

VERSION="$2"
NEW_VMLINUZ_PATH="/boot/vmlinuz-$VERSION" 
SET_VMLINUZ_PATH="/boot/vmlinuz-linux"

if [ ! -f "$NEW_VMLINUZ_PATH" ]; then 
	exit 0
fi

mv -f "$NEW_VMLINUZ_PATH" "$SET_VMLINUZ_PATH"
