#!/bin/zsh

current_battery=$(cat /sys/class/power_supply/BAT0/capacity)
state=$(cat /sys/class/power_supply/BAT0/status)

while true; do
	if [[ ${current_battery} -le 10 ]] && [[ ${state} != "Charging" ]]; then
		notify-send \
			-u critical \
			"Batterie wird leer!" \
			"Batterie bei ${current_battery}%. Lieber anstecken!"
	fi

	sleep 30
done
